spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3307/demooffloading?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: K59Ptl*100504
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

# Management / Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: order-service
  distribution:
    percentiles-histogram:
      http.server.requests: true
